#!/bin/bash -l
#SBATCH -A dp174
#SBATCH -p cosma6
#SBATCH --nodes 4
### NB cosma6 has 16 cores per node so product of these = 16
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=4
#SBATCH -o output_file.%J.out
#SBATCH -e error_file.%J.err
#
#SBATCH -t 1:00:00
#SBATCH -J JOBNAME
#SBATCH --exclusive
#SBATCH --mail-type=NONE             # notifications for job done & fail
#SBATCH --mail-user=james.bamber@physics.ox.ac.uk
module purge
#load the modules used to build your program.
module load intel_comp/2019 intel_mpi/2019 parallel_hdf5/1.10.3
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
# Run the program
export location=/cosma/home/dp174/dc-bamb1/Experimental_tools/InitialConditionSolver_with_ghosts
export application=Main_PoissonSolver3d.Linux.64.mpiicpc.ifort.OPTHIGH.MPI.OPENMPCC.ex
mpirun -np $SLURM_NTASKS ${location}${application} ../params.txt
